//@version=5
indicator("Andean Oscillator", overlay=true)
// Settings
lengthAnd     = input(50)
sig_length = input(9,'Signal Length')

// Exponential Envelopes
var alpha = 2 / (lengthAnd + 1)
var up1 = 0., var up2 = 0.
var dn1 = 0., var dn2 = 0.
C = close
O = open

up1 := nz(math.max(C, O, up1[1] - (up1[1] - C) * alpha), C)
up2 := nz(math.max(C * C, O * O, up2[1] - (up2[1] - C * C) * alpha), C * C)

dn1 := nz(math.min(C, O, dn1[1] + (C - dn1[1]) * alpha), C)
dn2 := nz(math.min(C * C, O * O, dn2[1] + (C * C - dn2[1]) * alpha), C * C)

// Components
bull = math.sqrt(dn2 - dn1 * dn1)
bear = math.sqrt(up2 - up1 * up1)

// Crossover Signals
bullishCross = ta.crossover(bull, bear)
bearishCross = ta.crossunder(bull, bear)

// Labels for Crossovers
if (bullishCross)
    label.new(x=bar_index, y=high, text="Up", color=color.green, textcolor=color.white, style=label.style_label_up, size=size.small)

if (bearishCross)
    label.new(x=bar_index, y=low, text="Down", color=color.red, textcolor=color.white, style=label.style_label_down, size=size.small)
